// src/可视化表格/components/dialogs/divination/CardBack.vue
<template>
  <div class="card-back">
    <img
      :src="imageUrl"
      alt="Tarot Card Back"
      class="card-back__image"
    />
    <div class="card-back__overlay"></div>
  </div>
</template>

<script setup lang="ts">
interface Props {
  /** 卡背图片 URL，默认使用神秘塔罗风格图片 */
  imageUrl?: string;
}

withDefaults(defineProps<Props>(), {
  imageUrl: 'https://i.postimg.cc/j2MPbGv3/IMG-1590.jpg',
});
</script>

// .kilocode/mystic-tarot-reader/components/CardBack.tsx
import React from 'react';

export const CardBack: React.FC = () => {
  return (
    <div className="w-full h-full rounded-xl overflow-hidden shadow-2xl border-[6px] border-[#4A3222] relative">
      <img 
        src="https://i.postimg.cc/j2MPbGv3/IMG-1590.jpg" 
        alt="Tarot Card Back" 
        className="w-full h-full object-cover"
      />
      {/* Subtle overlay to blend border */}
      <div className="absolute inset-0 border-[2px] border-[#8B5E3C]/50 rounded-lg pointer-events-none"></div>
    </div>
  );
};
